var x = 10;
var y = 20;
var z = x+y;
document.write("sum of " + x +" and "+ y+ " is "+ z);
document.write("<br>");
var x = 10;
var y = 20;
var z = x*y;
document.write("Multiplication of " + x +" and "+ y+ " is "+ z);
document.write("<br>");
var x = 10;
var y = 20;
var z = x-y;
document.write("subtraction of " + x +" and "+ y+ " is "+ z);
document.write("<br>");
var x = 10;
var y = 20;
var z = x/y;
document.write("division of " + x +" and "+ y+ " is "+ z);
document.write("<br>");
var x = 10;
var y = 20;
var z = x%y;
document.write("Modulus of " + x +" and "+ y+ " is "+ z);